"""Governance, power, and cooling health domain package for Miner Alerts (Spec 041).

Consolidates closed-loop thermal fan modulation, multi-miner preset balancing,
elevator electrical sensitivity analysis, cooling defect detection, and J/TH energy efficiency tracking.
"""

from __future__ import annotations

from app.governance.energy_efficiency import (
    STATUS_DEGRADED,
    STATUS_NORMAL,
    STATUS_OPTIMAL,
    EfficiencyAssessment,
    assess_miner_efficiency,
    build_efficiency_table_text,
    build_miner_efficiency_detail_text,
    calculate_efficiency_j_th,
    evaluate_efficiency_alerts,
    fetch_latest_efficiency_assessments,
)
from app.governance.fan_governor import (
    ACTION_EMERGENCY_SPIKE,
    ACTION_FAILSAFE_FAULT,
    ACTION_HOLD_DWELL,
    ACTION_HOLD_TARGET,
    ACTION_RECOVERY_MAX_COOLING,
    ACTION_STEP_DOWN,
    ACTION_STEP_UP,
    GovernorConfig,
    GovernorDecision,
    compute_governor_step,
)
from app.governance.fan_health import (
    STATUS_CRITICAL_HEAT,
    STATUS_ELEVATED,
    STATUS_FAN_DEFECT,
    STATUS_HEALTHY,
    STATUS_SATURATED,
    CoolingAssessment,
    assess_miner_cooling,
    build_fans_table_text,
    build_miner_fan_detail_text,
    calculate_thermal_headroom,
    evaluate_cooling_alerts,
)
from app.governance.preset_balancer import (
    ACTION_HOLD_STABLE,
    ACTION_LOCKED_MAX,
    ACTION_LOCKED_MIN,
    ACTION_STEP_DOWN_CASCADE,
    ACTION_STEP_DOWN_RESTARTS,
    ACTION_STEP_DOWN_THERMAL,
    ACTION_STEP_UP_OPTIMIZE,
    ACTION_UNKNOWN,
    BalancerConfig,
    BalancerDecision,
    DEFAULT_PRESET_LADDER,
    ElevatorSensitivitySummary,
    PresetTier,
    StabilityMetrics,
    analyze_elevator_sensitivity,
    build_balancer_table_text,
    build_elevator_sensitivity_text,
    build_miner_balancer_detail_text,
    compute_effective_hashrate,
    evaluate_balancer_step,
    extract_miner_stability_metrics,
    find_preset_index,
    infer_preset_name_from_power,
    record_elevator_restart_circumstance,
)

__all__ = [
    "ACTION_EMERGENCY_SPIKE",
    "ACTION_FAILSAFE_FAULT",
    "ACTION_HOLD_DWELL",
    "ACTION_HOLD_STABLE",
    "ACTION_HOLD_TARGET",
    "ACTION_LOCKED_MAX",
    "ACTION_LOCKED_MIN",
    "ACTION_RECOVERY_MAX_COOLING",
    "ACTION_STEP_DOWN",
    "ACTION_STEP_DOWN_CASCADE",
    "ACTION_STEP_DOWN_RESTARTS",
    "ACTION_STEP_DOWN_THERMAL",
    "ACTION_STEP_UP",
    "ACTION_STEP_UP_OPTIMIZE",
    "ACTION_UNKNOWN",
    "BalancerConfig",
    "BalancerDecision",
    "CoolingAssessment",
    "DEFAULT_PRESET_LADDER",
    "EfficiencyAssessment",
    "ElevatorSensitivitySummary",
    "GovernorConfig",
    "GovernorDecision",
    "PresetTier",
    "STATUS_CRITICAL_HEAT",
    "STATUS_DEGRADED",
    "STATUS_ELEVATED",
    "STATUS_FAN_DEFECT",
    "STATUS_HEALTHY",
    "STATUS_NORMAL",
    "STATUS_OPTIMAL",
    "STATUS_SATURATED",
    "StabilityMetrics",
    "analyze_elevator_sensitivity",
    "assess_miner_cooling",
    "assess_miner_efficiency",
    "build_balancer_table_text",
    "build_efficiency_table_text",
    "build_elevator_sensitivity_text",
    "build_fans_table_text",
    "build_miner_balancer_detail_text",
    "build_miner_efficiency_detail_text",
    "build_miner_fan_detail_text",
    "calculate_efficiency_j_th",
    "calculate_thermal_headroom",
    "compute_effective_hashrate",
    "compute_governor_step",
    "evaluate_balancer_step",
    "evaluate_cooling_alerts",
    "evaluate_efficiency_alerts",
    "extract_miner_stability_metrics",
    "fetch_latest_efficiency_assessments",
    "find_preset_index",
    "infer_preset_name_from_power",
    "record_elevator_restart_circumstance",
]
