"""Core domain package for Miner Alerts (Spec 041).

Consolidates low-level API 4028 network acquisition, SQLite EventStore persistence,
alert episode state machines, multi-source evidence fusion, liveness monitoring,
Prometheus metrics snapshots, mining quality evaluation, and reboot safety interlocks.
"""

from __future__ import annotations

from app.core.acquisition import (
    AcquisitionConfig,
    AcquisitionEpoch,
    Api4028Transport,
    Authority,
    BoundedAcquirer,
    DiagnosticProbeResult,
    EpisodeDiagnosticEnvelope,
    EpochScheduler,
    InFlightRegistry,
    MinerEndpoint,
    MinerSampleEnvelope,
    PollHealth,
    Quality,
    TransportOutcome,
    TransportStatus,
    dispatch_authoritative,
    validate_acquisition_config_dict,
)
from app.core.alert_episodes import (
    IRREGULAR_STATES,
    STATE_HASHBOARD,
    STATE_LOW,
    STATE_OFFLINE,
    STATE_OK,
    EpisodeNotificationBatch,
    EpisodeStep,
    IrregularEpisode,
    IrregularEpisodeCoordinator,
    format_current_status_line,
    render_episode_notification_batch,
)
from app.core.event_store import (
    SCHEMA_VERSION,
    EventStore,
    render_event_detail,
    render_event_list,
    render_reboot_decision,
)
from app.core.evidence_fusion import (
    RULESET_VERSION,
    CauseHypothesis,
    EvidenceFact,
    FusionConfig,
    IncidentAssessment,
    classify_freshness,
    compute_confidence_ceiling,
    compute_evidence_digest,
    detect_fleet_pattern,
    evaluate_hypothesis,
    is_within_attribution_window,
    map_clock_quality,
    max_cause_level,
    render_assessment_telegram,
    render_assessment_text,
    sort_facts_canonical,
    validate_fact_code,
)
from app.core.liveness import (
    HEARTBEAT_SCHEMA_VERSION,
    MonitorHeartbeat,
    assess_liveness,
    load_heartbeat,
    write_heartbeat_atomic,
)
from app.core.metrics_snapshot import (
    SNAPSHOT_SCHEMA_VERSION,
    MetricsSnapshot,
    load_metrics_snapshot,
    validate_snapshot_data,
    write_metrics_snapshot_atomic,
    write_monitor_metrics_snapshot_safe,
)
from app.core.mining_quality import (
    MiningQualityTelemetry,
    analyze_mining_quality,
    normalize_mining_quality,
    render_mining_quality,
)
from app.core.reboot_safety import (
    INTERLOCK_FIRMWARE_TRANSITION,
    INTERLOCK_FLEET_INCIDENT,
    INTERLOCK_HIGH_TEMPERATURE,
    RebootInterlockDecision,
    evaluate_auto_reboot_interlocks,
)
from app.core.restart_intelligence import (
    RestartClassification,
    classify_restart,
)
from app.core.stability_profile import (
    MetricBand,
    MetricRule,
    StabilityAssessment,
    analyze_stability,
    render_stability_assessment,
)

__all__ = [
    "AcquisitionConfig",
    "AcquisitionEpoch",
    "Api4028Transport",
    "Authority",
    "BoundedAcquirer",
    "CauseHypothesis",
    "DiagnosticProbeResult",
    "EpisodeDiagnosticEnvelope",
    "EpisodeNotificationBatch",
    "EpisodeStep",
    "EpochScheduler",
    "EventStore",
    "EvidenceFact",
    "FusionConfig",
    "HEARTBEAT_SCHEMA_VERSION",
    "INTERLOCK_FIRMWARE_TRANSITION",
    "INTERLOCK_FLEET_INCIDENT",
    "INTERLOCK_HIGH_TEMPERATURE",
    "IRREGULAR_STATES",
    "InFlightRegistry",
    "IncidentAssessment",
    "IrregularEpisode",
    "IrregularEpisodeCoordinator",
    "MetricBand",
    "MetricRule",
    "MetricsSnapshot",
    "MinerEndpoint",
    "MinerSampleEnvelope",
    "MiningQualityTelemetry",
    "MonitorHeartbeat",
    "PollHealth",
    "Quality",
    "RULESET_VERSION",
    "RebootInterlockDecision",
    "RestartClassification",
    "SCHEMA_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "STATE_HASHBOARD",
    "STATE_LOW",
    "STATE_OFFLINE",
    "STATE_OK",
    "StabilityAssessment",
    "TransportOutcome",
    "TransportStatus",
    "analyze_mining_quality",
    "analyze_stability",
    "classify_freshness",
    "classify_restart",
    "compute_confidence_ceiling",
    "compute_evidence_digest",
    "detect_fleet_pattern",
    "dispatch_authoritative",
    "evaluate_auto_reboot_interlocks",
    "evaluate_hypothesis",
    "format_current_status_line",
    "is_within_attribution_window",
    "load_heartbeat",
    "load_metrics_snapshot",
    "map_clock_quality",
    "max_cause_level",
    "normalize_mining_quality",
    "render_assessment_telegram",
    "render_assessment_text",
    "render_episode_notification_batch",
    "render_event_detail",
    "render_event_list",
    "render_mining_quality",
    "render_reboot_decision",
    "render_stability_assessment",
    "sort_facts_canonical",
    "validate_acquisition_config_dict",
    "validate_fact_code",
    "validate_snapshot_data",
    "write_heartbeat_atomic",
    "write_metrics_snapshot_atomic",
    "write_monitor_metrics_snapshot_safe",
]
